version: "3.9"

services:
    robot-domain-2:
        container_name: robot-domain-2
        image: docker.umanitobacssa.ca/cssa-ctf/web-robot-domain-2
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1001:80"