version: "3.9"

services:
    robot-domain-1:
        container_name: robot-domain-1
        image: docker.umanitobacssa.ca/cssa-ctf/web-robot-domain-1
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1000:80"